"""
WAF Detection Module
Detects Web Application Firewalls protecting a website.
"""

import argparse
import sys
import requests
from urllib3.exceptions import InsecureRequestWarning
from rich.console import Console
from rich.table import Table
from rich.panel import Panel

console = Console()
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-connecting-ip"],
        "cookie": ["__cfduid", "cf_clearance"],
        "body": ["cloudflare", "cf-browser-verification", "cloudflare-nginx"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "cookie": ["akamai"],
        "body": ["akamai", "reference #[\\d.]"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amzn-trace-id"],
        "cookie": ["aws-waf-token"],
        "body": ["aws-waf-token"],
    },
    "ModSecurity": {
        "headers": ["modsecurity", "server: mod_security"],
        "cookie": [],
        "body": ["mod_security", "modsecurity", "NOYB"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookie": ["sucuri"],
        "body": ["sucuri", "Access Denied by Sucuri"],
    },
    "Imperva": {
        "headers": ["x-iinfo"],
        "cookie": ["incap_ses", "visid_incap"],
        "body": ["imperva", "incapsula"],
    },
    "Barracuda": {
        "headers": [],
        "cookie": ["barra_counter_session"],
        "body": ["Barracuda", "barracuda_"],
    },
    "F5 BIG-IP": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookie": ["BIGipServer", "TS"],
        "body": ["BIG-IP", "BIGipServer"],
    },
    "Fortinet": {
        "headers": ["fortigate"],
        "cookie": ["SVPX", "APSCOOKIE"],
        "body": ["fortinet", "FortiGuard"],
    },
    "Varnish": {
        "headers": ["x-varnish", "via: varnish"],
        "cookie": [],
        "body": [],
    },
    "Nginx": {
        "headers": [],
        "cookie": [],
        "body": ["nginx"],
    },
    "Wordfence": {
        "headers": [],
        "cookie": ["wfwaf-authcookie"],
        "body": ["wordfence", "generated by Wordfence"],
    },
    "360WZB": {
        "headers": ["x-360wzb"],
        "cookie": [],
        "body": [],
    },
    "Yundun": {
        "headers": ["yundun"],
        "cookie": ["yundun"],
        "body": [],
    },
}

def detect_waf(url):
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    try:
        resp = requests.get(url, timeout=10, verify=False, allow_redirects=True)
    except requests.exceptions.RequestException as e:
        console.print(f"[bold red]Error:[/bold red] {e}")
        sys.exit(1)

    headers = {k.lower(): v for k, v in resp.headers.items()}
    cookies_str = str(resp.cookies)
    body = resp.text[:50000]

    detections = []

    for waf_name, signatures in WAF_SIGNATURES.items():
        score = 0
        matched = []

        # Check headers
        for h in signatures["headers"]:
            h_lower = h.lower()
            if h_lower.startswith("x-") or h_lower.startswith("cf-"):
                if h_lower in headers:
                    score += 3
                    matched.append(f"Header: {h}")
            else:
                if any(h_lower in k for k in headers):
                    score += 3
                    matched.append(f"Header: {h}")

        # Check cookies
        for c in signatures["cookie"]:
            if c.lower() in cookies_str.lower():
                score += 2
                matched.append(f"Cookie: {c}")

        # Check body
        import re
        for b in signatures["body"]:
            if re.search(b, body, re.IGNORECASE):
                score += 1
                matched.append(f"Body: {b}")

        if score > 0:
            detections.append({
                "name": waf_name,
                "score": score,
                "matches": matched
            })

    # Sort by score
    detections.sort(key=lambda x: x["score"], reverse=True)

    return {
        "url": url,
        "status": resp.status_code,
        "server": headers.get("server", "Unknown"),
        "detections": detections
    }

def run(raw_args=None):
    parser = argparse.ArgumentParser(description="WAF Detection")
    parser.add_argument("-u", "--url", required=True, help="Target URL")

    args = parser.parse_args(raw_args)

    result = detect_waf(args.url)

    console.print(f"[bold cyan]URL:[/bold cyan] {result['url']}")
    console.print(f"[bold cyan]Status:[/bold cyan] {result['status']}")
    console.print(f"[bold cyan]Server:[/bold cyan] {result['server']}\n")

    if result["detections"]:
        table = Table(title="WAF Detections", border_style="green", show_lines=True)
        table.add_column("WAF", style="bold cyan")
        table.add_column("Confidence", style="yellow")
        table.add_column("Matches", style="dim")

        for d in result["detections"]:
            confidence = "HIGH" if d["score"] >= 4 else "MEDIUM" if d["score"] >= 2 else "LOW"
            color = "red" if confidence == "HIGH" else "yellow" if confidence == "MEDIUM" else "dim"
            table.add_row(
                d["name"],
                f"[{color}]{confidence} ({d['score']})[/{color}]",
                "\n".join(d["matches"][:5])
            )

        console.print(table)
        console.print(f"\n[bold]Top detection:[/bold] {result['detections'][0]['name']}")
    else:
        console.print("[bold yellow]No WAF detected[/bold yellow]")
